CREATE DATABASE `test` 
CREATE TABLE post (userID INT, id   INT UNSIGNED AUTO_INCREMENT, title VARCHAR(200), body TEXT, PRIMARY KEY (id))
CREATE TABLE comment (postID INT, id INT UNSIGNED AUTO_INCREMENT, name VARCHAR(100), email VARCHAR(100), body TEXT, PRIMARY KEY (id))